# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)

In [3]:
print("Dimension (ndim):", A.ndim)
print("Shape:", A.shape)
print("Size:", A.size)
print("Datatype:", A.dtype)

Dimension (ndim): 2
Shape: (3, 5)
Size: 15
Datatype: int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [4]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [5]:
print("Elementwise subtraction:\n", B - C)
print("Elementwise multiplication:\n", B * C)
print("Matrix multiplication:\n", B @ C)

Elementwise subtraction:
 [[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
Elementwise multiplication:
 [[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
Matrix multiplication:
 [[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [6]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print("Exponentiated elements:\n", np.exp(B))
print("Minimum value in the whole matrix):", np.min(B))
print("Minimum value in each row:", np.min(B, axis=1))
print("Minimum value in each each column:", np.min(B, axis=0))
print("Index value for the minimum value in the whole matrix:", np.argmin(B))
print("index value for the minimum value in each row:", np.argmin(B, axis=1))
print("Sum of all elements:", np.sum(B))
print("Mean for each column:", np.mean(B, axis=0))
print("Median for each column:", np.median(B, axis=0))

Exponentiated elements:
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
Minimum value in the whole matrix): 1
Minimum value in each row: [1 4 7]
Minimum value in each each column: [1 2 3]
Index value for the minimum value in the whole matrix: 0
index value for the minimum value in each row: [0 0 0]
Sum of all elements: 45
Mean for each column: [4. 5. 6.]
Median for each column: [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [8]:
A = np.arange(1, 16).reshape(3,5)
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [9]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

När man anger färre index än antal axlar, returnerar NumPy hela delarrayen längs de återstående axlarna.
I exemplet A[1] hämtas rad 1 i matrisen, alltså hela den raden som en endimensionell array.
Det är samma sak som att skriva A[1, :].

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [10]:
A = np.arange(1, 16).reshape(3,5)

In [11]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


För att iterera element för element i en flerdimensionell array kan man använda .flat eller np.nditer():

In [12]:
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


eller

In [13]:
for i in np.nditer(A):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [14]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


Koden skapar först en array a med talen 0 till 29. Sedan formas arrayn om med .reshape((2, 3, -1)), vilket betyder att b får formen (2, 3, 5) d.v.s. en 3-dimensionell array, där första axeln (0) har 2 block, andra axeln (1) har 3 rader, och tredje axeln (2) har 5 kolumner. Argument -1 i reshape gör att NumPy automatiskt räknar ut det värdet utifrån det totala antalet element.

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [15]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [16]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [17]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [18]:
def add_mult_matrices(m1, m2, operation):
    # Kontrollera att båda indata är NumPy-arrayer
    if not isinstance(m1, np.ndarray) or not isinstance(m2, np.ndarray):
        raise TypeError("Båda indata måste vara NumPy-arrayer.")

    # Kontrollera att operationen är giltig ('add' eller 'multiply')
    if operation not in ['add', 'multiply']:
        raise ValueError("Operationen måste vara 'add' eller 'multiply'.")

    if operation == 'add':
        # Vid addition måste matriserna ha exakt samma form
        if m1.shape != m2.shape:
            raise ValueError("Vid addition måste matriserna ha samma form.")
        return m1 + m2

    if operation == 'multiply':
        # Vid multiplikation måste antalet kolumner i m1 matcha antalet rader i m2
        if m1.shape[1] != m2.shape[0]:
            raise ValueError("Vid multiplikation måste kolumnerna i första matrisen matcha raderna i andra.")
        return m1 @ m2  # Matrisprodukt

# Exempel 1: giltig addition (samma form)
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("Giltig addition:")
print(add_mult_matrices(A, B, 'add'))

# Exempel 2: ogiltig addition (olika form)
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 2, 3]])
try:
    print("\nOgiltig addition:")
    print(add_mult_matrices(A, B, 'add'))
except ValueError as e:
    print("Fel:", e)

# Exempel 3: giltig multiplikation (2x3 * 3x2)
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])
print("\nGiltig multiplikation:")
print(add_mult_matrices(A, B, 'multiply'))

# Exempel 4: ogiltig multiplikation (formfel)
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 2]])
try:
    print("\nOgiltig multiplikation:")
    print(add_mult_matrices(A, B, 'multiply'))
except ValueError as e:
    print("Fel:", e)


Giltig addition:
[[ 6  8]
 [10 12]]

Ogiltig addition:
Fel: Vid addition måste matriserna ha samma form.

Giltig multiplikation:
[[22 28]
 [49 64]]

Ogiltig multiplikation:
Fel: Vid multiplikation måste kolumnerna i första matrisen matcha raderna i andra.


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [25]:
# ----------------------------
# Uppgift 10.1.1 – Vektor x
# ----------------------------
print("### Uppgift 10.1.1")

x = np.array([4, 3])

# (a) Dimension
print("(a) Dimension av x:", x.shape)

# (b) 5x
print("(b) 5x:", 5 * x)

# (c) 3x
print("(c) 3x:", 3 * x)

# (d) 5x + 3x
print("(d) 5x + 3x:", 5 * x + 3 * x)

# (e) 8x
print("(e) 8x:", 8 * x)

# (f) 4x - x
print("(f) 4x - x:", 4 * x - x)

# (g) Transponering av x
x_T = x.T  # För 1D-array är transponeringen identisk
print("(g) x.T:", x_T, "Dimension:", x_T.shape)

# (h) x + x.T definierat?
print("(h) Är x + x.T definierat?", "Ja" if x.shape == x_T.shape else "Nej")

# (i) ||x||
print("(i) ||x||:", np.linalg.norm(x))


# ----------------------------
# Uppgift 10.1.2 – Vektor v
# ----------------------------
print("\n### Uppgift 10.1.2")

v = np.array([3, 7, 0, 11])

# (a) Dimension
print("(a) Dimension av v:", v.shape)

# (b) 2v
print("(b) 2v:", 2 * v)

# (c) 5v + 2v
print("(c) 5v + 2v:", 5 * v + 2 * v)

# (d) 4v - 2v
print("(d) 4v - 2v:", 4 * v - 2 * v)

# (e) Transponering av v
v_T = v.T  # Även här: 1D-array transponering förändrar inget
print("(e) v.T:", v_T, "Dimension:", v_T.shape)

# (f) ||v||
print("(f) ||v||:", np.linalg.norm(v))


# ----------------------------
# Uppgift 10.1.3 – Vektorer v1 och v2
# ----------------------------
print("\n ### Uppgift 10.1.3")

v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

# (a) ||v1||
print("(a) ||v1||:", np.linalg.norm(v1))

# (b) ||v1 - v2||
print("(b) ||v1 - v2||:", np.linalg.norm(v1 - v2))


### Uppgift 10.1.1
(a) Dimension av x: (2,)
(b) 5x: [20 15]
(c) 3x: [12  9]
(d) 5x + 3x: [32 24]
(e) 8x: [32 24]
(f) 4x - x: [12  9]
(g) x.T: [4 3] Dimension: (2,)
(h) Är x + x.T definierat? Ja
(i) ||x||: 5.0

### Uppgift 10.1.2
(a) Dimension av v: (4,)
(b) 2v: [ 6 14  0 22]
(c) 5v + 2v: [21 49  0 77]
(d) 4v - 2v: [ 6 14  0 22]
(e) v.T: [ 3  7  0 11] Dimension: (4,)
(f) ||v||: 13.379088160259652

 ### Uppgift 10.1.3
(a) ||v1||: 7.14142842854285
(b) ||v1 - v2||: 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [26]:
# ----------------------------
# Uppgift 10.2.1 – Matriser
# ----------------------------
print("### Uppgift 10.2.1")

A = np.array([[2, 1, -1], [1, -1, 1]])        # (2, 3)
B = np.array([[4, -2, 1], [2, -4, -2]])       # (2, 3)
C = np.array([[1, 2], [2, 1]])                # (2, 2)
D = np.array([[3, 4], [4, 3]])                # (2, 2)
E = np.array([[1], [2]])                      # (2, 1)
I = np.identity(2)                            # (2, 2)

print("(a) 2A:\n", 2 * A)
print("\n(b) B - 2A:\n", B - 2 * A)

# Broadcasting mellan (2,2) och (2,1) fungerar
print("\n(c) 3C - 2E:\n", 3 * C - 2 * E)

# C.T har form (2,2): kan subtraheras från D (också (2,2))
print("\n(d) 2D - 3Cᵀ:\n", 2 * D - 3 * C.T)

print("\n(e) Dᵀ + 2D:\n", D.T + 2 * D)
print("\n(f) 2Cᵀ - 2Dᵀ:\n", 2 * C.T - 2 * D.T)

# Subtraktion mellan A.T (3,2) och B (2,3) är ej möjlig
if A.T.shape != B.shape:
    print("\n(g) Aᵀ - B: Ej definierat (former:", A.T.shape, "och", B.shape, ")")
else:
    print("\n(g) Aᵀ - B:\n", A.T - B)

# Multiplikationer (kontrollera formkompatibilitet)
def safe_matmul(label, M1, M2):
    try:
        result = M1 @ M2
        print(f"{label}:\n", result)
    except ValueError as e:
        print(f"{label}: Ej definierat – {e}")

safe_matmul("\n(h) AC", A, C)
safe_matmul("\n(i) CD", C, D)
safe_matmul("\n(j) CB", C, B.T)  # C(2,2), B.T(3,2) → ej OK
safe_matmul("\n(k) CI", C, I)
safe_matmul("\n(l) ABᵀ", A, B.T)

# ----------------------------
# Uppgift 10.2.2 – AAᵀ
# ----------------------------
print("\n### Uppgift 10.2.2")

A2 = np.array([[2, 3, 4], [5, 4, 1]])
print("AAᵀ:\n", A2 @ A2.T)

# ----------------------------
# Uppgift 10.2.3 – Verifiera AB = AC men B ≠ C
# ----------------------------
print("\n### Uppgift 10.2.3")

A3 = np.array([[1, 2], [2, 4]])
B3 = np.array([[2, 1], [1, 3]])
C3 = np.array([[4, 3], [0, 2]])

AB = A3 @ B3
AC = A3 @ C3

print("AB:\n", AB)
print("AC:\n", AC)
print("B == C:", np.array_equal(B3, C3))
print("AB == AC:", np.array_equal(AB, AC))


### Uppgift 10.2.1
(a) 2A:
 [[ 4  2 -2]
 [ 2 -2  2]]

(b) B - 2A:
 [[ 0 -4  3]
 [ 0 -2 -4]]

(c) 3C - 2E:
 [[ 1  4]
 [ 2 -1]]

(d) 2D - 3Cᵀ:
 [[3 2]
 [2 3]]

(e) Dᵀ + 2D:
 [[ 9 12]
 [12  9]]

(f) 2Cᵀ - 2Dᵀ:
 [[-4 -4]
 [-4 -4]]

(g) Aᵀ - B: Ej definierat (former: (3, 2) och (2, 3) )

(h) AC: Ej definierat – matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

(i) CD:
 [[11 10]
 [10 11]]

(j) CB: Ej definierat – matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

(k) CI:
 [[1. 2.]
 [2. 1.]]

(l) ABᵀ:
 [[5 2]
 [7 4]]

### Uppgift 10.2.2
AAᵀ:
 [[29 26]
 [26 42]]

### Uppgift 10.2.3
AB:
 [[ 4  7]
 [ 8 14]]
AC:
 [[ 4  7]
 [ 8 14]]
B == C: False
AB == AC: True


In [27]:
# ----------------------------
# Uppgift 10.2.4 – Skriv på formen Ax = b och verifiera
# ----------------------------
print("\n### Uppgift 10.2.4")

# Matris A med koefficienter
A = np.array([
    [3, 2, 4],
    [2, 3, 8],
    [4, 1, 3],
    [7, 1, 5]
])

# Vektor b med högerled
b = np.array([7, 4, 11, 9])

# Kontroll: beräkna en godtycklig lösning med t.ex. np.linalg.lstsq (minsta kvadratmetoden)
x, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)

print("Lösning x:\n", x)

# Verifiera att Ax ≈ b
b_check = A @ x
print("Ax =\n", b_check)

# Skillnad (avrundningsfel bör vara små)
print("Skillnad Ax - b:\n", b_check - b)



### Uppgift 10.2.4
Lösning x:
 [ 2.13691417  4.83412322 -1.89152185]
Ax =
 [ 8.51290153  3.64402317  7.70721432 10.33491311]
Skillnad Ax - b:
 [ 1.51290153 -0.35597683 -3.29278568  1.33491311]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [28]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [29]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [30]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


Ja, det sista elementet i v1 ändras eftersom v2 är en vy av v1, inte en kopia.
Man kan kontrollera detta med attributet .base. 
Om v2.base pekar på v1, betyder det att v2 delar samma minne som v1.
När man använder vanlig slicing (t.ex. v1[-2:]) i NumPy skapas en vy, inte en kopia. 
Detta innebär att ändringar i v2 också påverkar v1, eftersom båda pekar på samma data i minnet.